[2024-12-16T14:17:37.329+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: All_Layer.clean_review manual__2024-12-16T14:17:20.331942+00:00 [queued]>
[2024-12-16T14:17:37.350+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: All_Layer.clean_review manual__2024-12-16T14:17:20.331942+00:00 [queued]>
[2024-12-16T14:17:37.351+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-16T14:17:37.371+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): clean_review> on 2024-12-16 14:17:20.331942+00:00
[2024-12-16T14:17:37.381+0000] {standard_task_runner.py:57} INFO - Started process 664 to run task
[2024-12-16T14:17:37.385+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'All_Layer', 'clean_review', 'manual__2024-12-16T14:17:20.331942+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/All_Offi.py', '--cfg-path', '/tmp/tmp8ixicui6']
[2024-12-16T14:17:37.389+0000] {standard_task_runner.py:85} INFO - Job 215: Subtask clean_review
[2024-12-16T14:17:37.477+0000] {task_command.py:416} INFO - Running <TaskInstance: All_Layer.clean_review manual__2024-12-16T14:17:20.331942+00:00 [running]> on host a2b73f6a4b3a
[2024-12-16T14:17:37.597+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='All_Layer' AIRFLOW_CTX_TASK_ID='clean_review' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T14:17:20.331942+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T14:17:20.331942+00:00'
[2024-12-16T14:17:37.610+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-12-16T14:17:37.613+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 1g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_review.py s3a://lakehouse/bronze/review.parquet s3a://lakehouse/sliver/review
[2024-12-16T14:17:37.952+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-12-16T14:17:43.510+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-12-16T14:17:43.932+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2024-12-16T14:17:43.935+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2024-12-16T14:17:43.956+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-12-16T14:17:43.970+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-890bfaf6-b0ec-4434-a5f2-e4b4d6c7db6f;1.0
[2024-12-16T14:17:43.971+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-12-16T14:17:44.421+0000] {spark_submit.py:579} INFO - found org.apache.hadoop#hadoop-aws;3.3.4 in spark-list
[2024-12-16T14:17:44.489+0000] {spark_submit.py:579} INFO - found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
[2024-12-16T14:17:44.632+0000] {spark_submit.py:579} INFO - found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in spark-list
[2024-12-16T14:17:44.736+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 719ms :: artifacts dl 47ms
[2024-12-16T14:17:44.743+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-12-16T14:17:44.744+0000] {spark_submit.py:579} INFO - com.amazonaws#aws-java-sdk-bundle;1.12.262 from central in [default]
[2024-12-16T14:17:44.750+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws;3.3.4 from spark-list in [default]
[2024-12-16T14:17:44.752+0000] {spark_submit.py:579} INFO - org.wildfly.openssl#wildfly-openssl;1.0.7.Final from spark-list in [default]
[2024-12-16T14:17:44.753+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-12-16T14:17:44.753+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-12-16T14:17:44.754+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-12-16T14:17:44.754+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-12-16T14:17:44.755+0000] {spark_submit.py:579} INFO - |      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2024-12-16T14:17:44.755+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-12-16T14:17:44.758+0000] {spark_submit.py:579} INFO - 
[2024-12-16T14:17:44.758+0000] {spark_submit.py:579} INFO - :: problems summary ::
[2024-12-16T14:17:44.759+0000] {spark_submit.py:579} INFO - :::: ERRORS
[2024-12-16T14:17:44.759+0000] {spark_submit.py:579} INFO - unknown resolver null
[2024-12-16T14:17:44.760+0000] {spark_submit.py:579} INFO - 
[2024-12-16T14:17:44.760+0000] {spark_submit.py:579} INFO - unknown resolver null
[2024-12-16T14:17:44.761+0000] {spark_submit.py:579} INFO - 
[2024-12-16T14:17:44.761+0000] {spark_submit.py:579} INFO - 
[2024-12-16T14:17:44.762+0000] {spark_submit.py:579} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2024-12-16T14:17:44.764+0000] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-890bfaf6-b0ec-4434-a5f2-e4b4d6c7db6f
[2024-12-16T14:17:44.765+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-12-16T14:17:44.815+0000] {spark_submit.py:579} INFO - 0 artifacts copied, 3 already retrieved (0kB/46ms)
[2024-12-16T14:17:45.546+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-12-16T14:17:47.817+0000] {spark_submit.py:579} INFO - 2024-12-16 14:17:47,817 INFO: Initializing Spark session...
[2024-12-16T14:17:48.128+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SparkContext: Running Spark version 3.3.2
[2024-12-16T14:17:48.185+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceUtils: ==============================================================
[2024-12-16T14:17:48.187+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-12-16T14:17:48.189+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceUtils: ==============================================================
[2024-12-16T14:17:48.190+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SparkContext: Submitted application: CleanReview
[2024-12-16T14:17:48.237+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 2, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-12-16T14:17:48.259+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceProfile: Limiting resource is cpus at 2 tasks per executor
[2024-12-16T14:17:48.264+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-12-16T14:17:48.383+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SecurityManager: Changing view acls to: ***
[2024-12-16T14:17:48.386+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SecurityManager: Changing modify acls to: ***
[2024-12-16T14:17:48.391+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SecurityManager: Changing view acls groups to:
[2024-12-16T14:17:48.392+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SecurityManager: Changing modify acls groups to:
[2024-12-16T14:17:48.392+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2024-12-16T14:17:49.329+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO Utils: Successfully started service 'sparkDriver' on port 39625.
[2024-12-16T14:17:49.365+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO SparkEnv: Registering MapOutputTracker
[2024-12-16T14:17:49.434+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO SparkEnv: Registering BlockManagerMaster
[2024-12-16T14:17:49.472+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-12-16T14:17:49.474+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-12-16T14:17:49.497+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-12-16T14:17:49.572+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-f38e9f08-883a-4b01-9509-ae76cfa0c0d6
[2024-12-16T14:17:49.629+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-12-16T14:17:49.659+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-12-16T14:17:50.047+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-12-16T14:17:50.126+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///opt/***/jars/hadoop-aws-3.3.4.jar at spark://a2b73f6a4b3a:39625/jars/hadoop-aws-3.3.4.jar with timestamp 1734358668087
[2024-12-16T14:17:50.130+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///opt/***/jars/s3-2.18.41.jar at spark://a2b73f6a4b3a:39625/jars/s3-2.18.41.jar with timestamp 1734358668087
[2024-12-16T14:17:50.132+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///opt/***/jars/aws-java-sdk-1.12.367.jar at spark://a2b73f6a4b3a:39625/jars/aws-java-sdk-1.12.367.jar with timestamp 1734358668087
[2024-12-16T14:17:50.136+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///opt/***/jars/delta-core_2.12-2.2.0.jar at spark://a2b73f6a4b3a:39625/jars/delta-core_2.12-2.2.0.jar with timestamp 1734358668087
[2024-12-16T14:17:50.141+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///opt/***/jars/delta-storage-2.2.0.jar at spark://a2b73f6a4b3a:39625/jars/delta-storage-2.2.0.jar with timestamp 1734358668087
[2024-12-16T14:17:50.144+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar at spark://a2b73f6a4b3a:39625/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar with timestamp 1734358668087
[2024-12-16T14:17:50.145+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar at spark://a2b73f6a4b3a:39625/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar with timestamp 1734358668087
[2024-12-16T14:17:50.147+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar at spark://a2b73f6a4b3a:39625/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar with timestamp 1734358668087
[2024-12-16T14:17:50.155+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar at spark://a2b73f6a4b3a:39625/files/org.apache.hadoop_hadoop-aws-3.3.4.jar with timestamp 1734358668087
[2024-12-16T14:17:50.161+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar to /tmp/spark-bff6371b-9375-4c93-b750-4e704fb85297/userFiles-b5379c93-1e63-4d15-98a1-86fa3cd47d90/org.apache.hadoop_hadoop-aws-3.3.4.jar
[2024-12-16T14:17:50.247+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added file file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar at spark://a2b73f6a4b3a:39625/files/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar with timestamp 1734358668087
[2024-12-16T14:17:50.247+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO Utils: Copying /home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar to /tmp/spark-bff6371b-9375-4c93-b750-4e704fb85297/userFiles-b5379c93-1e63-4d15-98a1-86fa3cd47d90/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar
[2024-12-16T14:17:52.330+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:52 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar at spark://a2b73f6a4b3a:39625/files/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar with timestamp 1734358668087
[2024-12-16T14:17:52.331+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:52 INFO Utils: Copying /home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar to /tmp/spark-bff6371b-9375-4c93-b750-4e704fb85297/userFiles-b5379c93-1e63-4d15-98a1-86fa3cd47d90/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar
[2024-12-16T14:17:52.599+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:52 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-12-16T14:17:52.701+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:52 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.5:7077 after 59 ms (0 ms spent in bootstraps)
[2024-12-16T14:17:54.083+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241216141754-0004
[2024-12-16T14:17:54.095+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40353.
[2024-12-16T14:17:54.096+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO NettyBlockTransferService: Server created on a2b73f6a4b3a:40353
[2024-12-16T14:17:54.098+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-12-16T14:17:54.108+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, a2b73f6a4b3a, 40353, None)
[2024-12-16T14:17:54.114+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO BlockManagerMasterEndpoint: Registering block manager a2b73f6a4b3a:40353 with 434.4 MiB RAM, BlockManagerId(driver, a2b73f6a4b3a, 40353, None)
[2024-12-16T14:17:54.120+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, a2b73f6a4b3a, 40353, None)
[2024-12-16T14:17:54.122+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, a2b73f6a4b3a, 40353, None)
[2024-12-16T14:17:54.563+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-12-16T14:17:55.011+0000] {spark_submit.py:579} INFO - 2024-12-16 14:17:55,011 INFO: Spark session initialized successfully.
[2024-12-16T14:17:55.012+0000] {spark_submit.py:579} INFO - 2024-12-16 14:17:55,011 INFO: Reading data from s3a://lakehouse/bronze/review.parquet
[2024-12-16T14:17:55.025+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:55 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-12-16T14:17:55.347+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:55 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2024-12-16T14:17:55.376+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:55 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2024-12-16T14:17:55.376+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:55 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2024-12-16T14:17:57.768+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:57 INFO SharedState: Warehouse path is 's3a://lakehouse/'.
[2024-12-16T14:18:00.968+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:00 INFO InMemoryFileIndex: It took 261 ms to list leaf files for 1 paths.
[2024-12-16T14:18:03.877+0000] {spark_submit.py:579} INFO - 2024-12-16 14:18:03,877 INFO: Cleaning data...
[2024-12-16T14:18:04.130+0000] {spark_submit.py:579} INFO - 2024-12-16 14:18:04,129 INFO: Saving cleaned data to s3a://lakehouse/sliver/review
[2024-12-16T14:18:05.675+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:05 INFO DeltaLog: Creating initial snapshot without metadata, because the directory is empty
[2024-12-16T14:18:05.962+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:05 INFO InitialSnapshot: [tableId=b846a458-6fe2-4d6d-b63c-2e6c28ba3411] Created snapshot InitialSnapshot(path=s3a://lakehouse/sliver/review/_delta_log, version=-1, metadata=Metadata(1044ea5c-5886-4cf5-b4ca-70863eac422c,null,null,Format(parquet,Map()),null,List(),Map(),Some(1734358685945)), logSegment=LogSegment(s3a://lakehouse/sliver/review/_delta_log,-1,List(),List(),None,-1), checksumOpt=None)
[2024-12-16T14:18:06.102+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:06 INFO DeltaLog: No delta log found for the Delta table at s3a://lakehouse/sliver/review/_delta_log
[2024-12-16T14:18:06.103+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:06 INFO InitialSnapshot: [tableId=1044ea5c-5886-4cf5-b4ca-70863eac422c] Created snapshot InitialSnapshot(path=s3a://lakehouse/sliver/review/_delta_log, version=-1, metadata=Metadata(1cfcc470-fba4-4367-9bd6-0a2c64b4a7f1,null,null,Format(parquet,Map()),null,List(),Map(),Some(1734358686103)), logSegment=LogSegment(s3a://lakehouse/sliver/review/_delta_log,-1,List(),List(),None,-1), checksumOpt=None)
[2024-12-16T14:18:06.140+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:06 INFO OptimisticTransaction: [tableId=1cfcc470,txnId=98dae958] Updated metadata from - to Metadata(7c516b42-6c27-4a57-82a0-f45fcf25913a,null,null,Format(parquet,Map()),{"type":"struct","fields":[{"name":"review","type":"string","nullable":true,"metadata":{}},{"name":"sentiment","type":"string","nullable":true,"metadata":{}}]},List(),Map(),Some(1734358686127))
[2024-12-16T14:18:07.064+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:07 INFO FileSourceStrategy: Pushed Filters:
[2024-12-16T14:18:07.066+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:07 INFO FileSourceStrategy: Post-Scan Filters: atleastnnonnulls(2, review#0, sentiment#1)
[2024-12-16T14:18:07.071+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:07 INFO FileSourceStrategy: Output Data Schema: struct<review: string, sentiment: string>
[2024-12-16T14:18:07.259+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:07 INFO DeltaParquetFileFormat: Using default output committer for Parquet: org.apache.parquet.hadoop.ParquetOutputCommitter
[2024-12-16T14:18:07.383+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:07 INFO HashAggregateExec: spark.sql.codegen.aggregate.map.twolevel.enabled is set to true, but current version of codegened fast hashmap does not support this aggregate.
[2024-12-16T14:18:07.721+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:07 INFO CodeGenerator: Code generated in 272.827015 ms
[2024-12-16T14:18:07.791+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:07 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 206.3 KiB, free 434.2 MiB)
[2024-12-16T14:18:07.971+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:07 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 36.2 KiB, free 434.2 MiB)
[2024-12-16T14:18:07.976+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:07 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on a2b73f6a4b3a:40353 (size: 36.2 KiB, free: 434.4 MiB)
[2024-12-16T14:18:07.984+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:07 INFO SparkContext: Created broadcast 0 from save at NativeMethodAccessorImpl.java:0
[2024-12-16T14:18:08.008+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO FileSourceScanExec: Planning scan with bin packing, max size: 23437026 bytes, open cost is considered as scanning 4194304 bytes.
[2024-12-16T14:18:08.384+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO DAGScheduler: Registering RDD 3 (save at NativeMethodAccessorImpl.java:0) as input to shuffle 0
[2024-12-16T14:18:08.390+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO DAGScheduler: Got map stage job 0 (save at NativeMethodAccessorImpl.java:0) with 2 output partitions
[2024-12-16T14:18:08.391+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO DAGScheduler: Final stage: ShuffleMapStage 0 (save at NativeMethodAccessorImpl.java:0)
[2024-12-16T14:18:08.392+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO DAGScheduler: Parents of final stage: List()
[2024-12-16T14:18:08.392+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO DAGScheduler: Missing parents: List()
[2024-12-16T14:18:08.398+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO DAGScheduler: Submitting ShuffleMapStage 0 (MapPartitionsRDD[3] at save at NativeMethodAccessorImpl.java:0), which has no missing parents
[2024-12-16T14:18:08.451+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 26.0 KiB, free 434.1 MiB)
[2024-12-16T14:18:08.468+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 11.3 KiB, free 434.1 MiB)
[2024-12-16T14:18:08.470+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on a2b73f6a4b3a:40353 (size: 11.3 KiB, free: 434.4 MiB)
[2024-12-16T14:18:08.472+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1513
[2024-12-16T14:18:08.491+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO DAGScheduler: Submitting 2 missing tasks from ShuffleMapStage 0 (MapPartitionsRDD[3] at save at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0, 1))
[2024-12-16T14:18:08.495+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:08 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks resource profile 0
[2024-12-16T14:18:23.524+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:23 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:18:38.523+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:38 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:18:53.523+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:53 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:19:08.808+0000] {spark_submit.py:579} INFO - 24/12/16 14:19:08 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:19:23.750+0000] {spark_submit.py:579} INFO - 24/12/16 14:19:23 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:19:22.236+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-12-16T14:19:45.423+0000] {spark_submit.py:579} INFO - 24/12/16 14:19:38 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:20:03.779+0000] {spark_submit.py:579} INFO - 24/12/16 14:19:54 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:19:54.018+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-12-16T14:20:09.125+0000] {spark_submit.py:579} INFO - 24/12/16 14:20:09 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:20:14.624+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-16T14:20:14.644+0000] {process_utils.py:131} INFO - Sending 15 to group 664. PIDs of all processes in the group: [668, 968, 664]
[2024-12-16T14:20:14.655+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 664
[2024-12-16T14:20:14.660+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-16T14:20:14.662+0000] {spark_submit.py:705} INFO - Sending kill signal to spark-submit
[2024-12-16T14:20:14.720+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 493, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 542, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-16T14:20:14.763+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=All_Layer, task_id=clean_review, execution_date=20241216T141720, start_date=20241216T141737, end_date=20241216T142014
[2024-12-16T14:20:14.963+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 215 for task clean_review (Task received SIGTERM signal; 664)
[2024-12-16T14:20:15.011+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=968, status='terminated', started='14:17:46') (968) terminated with exit code None
[2024-12-16T14:20:15.030+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=664, status='terminated', exitcode=1, started='14:17:37') (664) terminated with exit code 1
[2024-12-16T14:20:15.033+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=668, status='terminated', started='14:17:37') (668) terminated with exit code None
