[2024-12-16T14:16:04.715+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: All_Layer.bronze_ratings scheduled__2024-12-15T00:00:00+00:00 [queued]>
[2024-12-16T14:16:04.728+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: All_Layer.bronze_ratings scheduled__2024-12-15T00:00:00+00:00 [queued]>
[2024-12-16T14:16:04.729+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2024-12-16T14:16:04.751+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): bronze_ratings> on 2024-12-15 00:00:00+00:00
[2024-12-16T14:16:04.761+0000] {standard_task_runner.py:57} INFO - Started process 472 to run task
[2024-12-16T14:16:04.768+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'All_Layer', 'bronze_ratings', 'scheduled__2024-12-15T00:00:00+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/All_Offi.py', '--cfg-path', '/tmp/tmpdkvzp04k']
[2024-12-16T14:16:04.772+0000] {standard_task_runner.py:85} INFO - Job 196: Subtask bronze_ratings
[2024-12-16T14:16:04.871+0000] {task_command.py:416} INFO - Running <TaskInstance: All_Layer.bronze_ratings scheduled__2024-12-15T00:00:00+00:00 [running]> on host a2b73f6a4b3a
[2024-12-16T14:16:04.982+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='All_Layer' AIRFLOW_CTX_TASK_ID='bronze_ratings' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-15T00:00:00+00:00'
[2024-12-16T14:16:15.050+0000] {All_Offi.py:95} ERROR - Error in bronze_ratings task: 'DataFrame' object has no attribute 'limit'
[2024-12-16T14:16:15.052+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/All_Offi.py", line 96, in bronze_ratings
    raise e
  File "/opt/airflow/dags/All_Offi.py", line 91, in bronze_ratings
    df = get_data_from_raw('ratings').limit(50000)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'limit'
[2024-12-16T14:16:15.075+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=All_Layer, task_id=bronze_ratings, execution_date=20241215T000000, start_date=20241216T141604, end_date=20241216T141615
[2024-12-16T14:16:15.093+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 196 for task bronze_ratings ('DataFrame' object has no attribute 'limit'; 472)
[2024-12-16T14:16:15.126+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-16T14:16:15.155+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
